### ISSUE TITLE
Vertex pushing

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#128]
Black box vertices can be pushed around when following this procedure. I feel like someone has reported/mentioned this before, but here it is anyway. This "pushing" affects the vertices in Investigate mode, and the pre-made "revealed" circuits:

![cckbb04](https://cloud.githubusercontent.com/assets/5863899/15836947/67aa893e-2bf4-11e6-8a4a-cd209beeb1d9.gif)

For #126.

**Comment by arouinfar** [comment]
@phet-steele mentioned this is likely related to #125.

**Comment by samreid** [comment]
I think we should add a rule that components cannot be connected when outside of the black box in build mode.

**Comment by samreid** [comment]
I added a rule in #113 that the interface vertices cannot be moved, it seems to have covered this case, closing.

**Comment by samreid** [comment]
Or shall I say, fixed pending testing.

**Comment by samreid** [comment]
Ready for testing in https://github.com/phetsims/circuit-construction-kit/issues/134

**Comment by arouinfar** [comment]
Somethings still not quite right here @samreid. 

> I think we should add a rule that components cannot be connected when outside of the black box in build mode.

If I connect a fixed-length component to the outside of the black box in Build mode, it remains outside. I can continue to build outside of the black box if I connect other fixed-length components to the first one.

![externalnodes](https://cloud.githubusercontent.com/assets/8419308/16059910/6454fb08-3242-11e6-915c-972ccc453a24.gif)

After deleting the battery attached to the black box, the other battery floats in the playspace. It does not snap to the inside of the black box until it is clicked.

To avoid this issue, would it be possible for fixed-length components to rotate into the black box if they are connected to a black box vertex from the outside? Sort of like this:
![batteryrotation](https://cloud.githubusercontent.com/assets/8419308/16060881/421ae96c-3247-11e6-8b25-55319cc1f2dd.gif)

Assigning to @phet-steele to be on the lookout for additional related issues when he works on #134.

**Comment by samreid** [comment]
I'll move the "connecting objects outside the black box" to a new issue, and this issue can remain to be focused on vertex pushing.

**Comment by samreid** [comment]
@arouinfar now that the "connecting objects outside the black box" is moved to a separate issue, can this issue (about vertex pushing) be closed?

**Comment by arouinfar** [comment]
@samreid I ran into another instance of vertex pushing. If a fixed-length component is in the path of a wire that snaps into the box, such that their vertices are within the snap-to-connect distance, it's possible for the vertex of the fixed-length component to be dislocated.
![vertexpushing2](https://cloud.githubusercontent.com/assets/8419308/16159718/8bcc2bde-3481-11e6-9d27-14b3be2f5d69.gif)

**Comment by samreid** [comment]
Thanks @arouinfar, this may be solved if we expand the rules of #136 to say that a component cannot propose a connection inside a black box if any of its vertices are outside of the black box.  Sound like it is worth investigating?

**Comment by arouinfar** [comment]
@samreid that sounds like a reasonable rule. Please look into it.

**Comment by samreid** [comment]
I implemented that as described and it seems like it is working well.  Will be ready for testing in next version.

**Comment by samreid** [comment]
Please refer to https://github.com/phetsims/circuit-construction-kit/issues/140 for testing.

**Comment by phet-steele** [comment]
@samreid the procedure in https://github.com/phetsims/circuit-construction-kit/issues/128#issuecomment-226837158 still happens in 1.0.0-dev.17.

**Comment by phet-steele** [comment]
@arouinfar @samreid aside from the issues pointed out in #141, I'm not a huge fan of this proposed rule (https://github.com/phetsims/circuit-construction-kit/issues/128#issuecomment-226837685) in general. It is not good at handling vertices along the top and bottom of the black box. It's very frustrating to try to make connections and also causes some intense flickering while dragging (not captured well in this low frame rate video):
![cckbb08](https://cloud.githubusercontent.com/assets/5863899/16238168/b224096e-379c-11e6-9ddf-5cebe0b21bff.gif)

**Comment by samreid** [comment]
Proposed fix above.  I expanded the black box bounds outward so that the black box vertices are in bounds and it seems to help.  This will need testing.  Will moving the black box bounds outward cause other problems?  Let's find out in the next test version.

**Comment by samreid** [comment]
Testing issue linked above.

**Comment by phet-steele** [comment]
@samreid I'm still getting a lot of flickering.

**Comment by samreid** [comment]
Same as in https://github.com/phetsims/circuit-construction-kit-common/issues/128#issuecomment-227498773 ?

**Comment by phet-steele** [comment]
@samreid yes

**Comment by samreid** [comment]
Are you still seeing flickering for perfectly horizontal components, or only for near-horizontal components?

**Comment by phet-steele** [comment]
Only near-horizontal. The initial drag from the component box performs optimally.

**Comment by samreid** [comment]
I'll move this last issue to a new separate issue.

**Comment by phet-steele** [comment]
@samreid I believe https://github.com/phetsims/circuit-construction-kit-common/issues/128#issuecomment-226837158 is still present.

**Comment by samreid** [comment]
Thanks @phet-steele, I'll create a specific issue for that problem.

**Comment by samreid** [comment]
Tracking the remaining issue in #173, closing.
