### ISSUE TITLE
Black vertex with no connection

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#176]
From the newly implemented #163, black box external vertices in Investigate mode show as black and with solder when cutting a connection. Switching build modes remedies the problem:

![cckbbs01](https://cloud.githubusercontent.com/assets/5863899/16810309/a797abc2-48e0-11e6-8993-1eae4d3a71f7.gif)

Seen on Win 10 Chrome. For phetsims/tasks/issues/643.
Troubleshooting information:
Name: ‪Circuit Construction Kit: Black Box Study‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.19/circuit-construction-kit-black-box-study_en.html
Version: 1.0.0-dev.19 2016-07-12 22:00:54 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1536x739
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"5b1f70f3","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"8825397d","branch":"master"},"circuit-construction-kit-black-box-study":{"sha":"0496b8ff","branch":"master"},"circuit-construction-kit-common":{"sha":"9c38befc","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"0d6b589e","branch":"master"},"sherpa":{"sha":"03590a07","branch":"master"},"sun":{"sha":"b4a2dc38","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"}}

**Comment by phet-steele** [comment]
As a continuation after the disconnection step in the video above (before the switch between view modes), making another connection to a different black box vertex also fixes the problem...except that the dashed circle layering is a little off:

![cckbb13](https://cloud.githubusercontent.com/assets/5863899/16848565/91acc3b4-49b3-11e6-88d8-8e075df6471f.gif)

**Comment by samreid** [comment]
This appears fixed in master, closing.

**Comment by phet-steele** [comment]
@samreid this is what I see in rc.3. Granted it is slightly different since the left over vertex is red instead of black. The procedure is still the same and shows solder on a vertex with no connections.
![cckbbio10](https://cloud.githubusercontent.com/assets/5863899/22999477/dd99b982-f398-11e6-87be-75904002746d.gif)

**Comment by samreid** [comment]
Moved to BBS issue, closing.
