### ISSUE TITLE
documentation of query parameters

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#581]
Related to https://github.com/phetsims/aqua/issues/91.

In CCKCQueryParameters.js and CCKACQueryParameters.js, there is no indication that any of the query parameters are public-facing (no use of `public` field in schema), and some query parameters are not even documented.

**Comment by samreid** [comment]
Fixed in the commit and ready for review.

**Comment by pixelzoom** [comment]
> ...  (no use of `public` field in schema) ...


I still don't see any use of `public`.  Public-facing query parameter need to have `public: true` or they won't be handled by QueryParameterWarningDialog.  For example in NS:

```js
  // Determines whether allele abbreviations are visible in the UI. Setting this to false hides the Pedigree 'Alleles'
  // panel, makes the Pedigree graph wider, and allele abbreviations will not be shown in the Pedigree graph.
  allelesVisible: {
    type: 'boolean',
    defaultValue: true,
    public: true
  },
```

**Comment by samreid** [comment]
Thanks, I added that in the commit.  Back to you for mini-review.

**Comment by pixelzoom** [comment]
👍🏻 closing.
