### ISSUE TITLE
Chart tool icon labels should disappear when "Labels" is unchecked.

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#794]
Discovered during https://github.com/phetsims/circuit-construction-kit-common/issues/513 and relevant to https://github.com/phetsims/qa/issues/748.

Chart tool icon labels should disappear when "Labels" is unchecked.

![image](https://user-images.githubusercontent.com/679486/144721208-e8f6c301-c2e1-48d2-a658-30fc87b79b4d.png)

**Comment by samreid** [comment]
Fixed in the commit and ready for cherry-picking into the release branch.

**Comment by KatieWoe** [comment]
This is still in RC.2. Not fixed
![notfixed](https://user-images.githubusercontent.com/41024075/145634013-aeb7b523-ddb8-40cd-b0c7-0a9264443431.gif)

**Comment by KatieWoe** [comment]
Actually, I think I may have misunderstood/misread. Waiting for SR to confirm.

**Comment by samreid** [comment]
I wrote on slack:

> The desired behavior is that labels would disappear when the “labels” checkbox is unchecked.  That was broken in RC.1.  In the gif you provided, I can see that the “Voltage chart” and “Current chart” labels correctly disappear when “labels” is unchecked, so that seems fixed.

**Comment by KatieWoe** [comment]
Sorry for the confussion
