### ISSUE TITLE
Cursor hand over region with no chart tool icon

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#795]
Discovered during https://github.com/phetsims/circuit-construction-kit-common/issues/513 and relevant to https://github.com/phetsims/qa/issues/748.

Even after dragging out all the charts, there is still a cursor hand in that region.

**Comment by samreid** [comment]
Fixed in master and ready for cherry-picking into the RC branch.

**Comment by KatieWoe** [comment]
This is partially fixed. Now, when all charts are removed the label disappears. This may be intended, but for the ammeters on the lab screen, it only takes the left ammeter into account, and the label disappears even if in-line ammeters are left. This does not occur if all in-line ammeters are removed but the left ammeters are left.
![ammetergone](https://user-images.githubusercontent.com/41024075/145635333-93eac71d-5c10-4b0d-98a2-dad6497a43dc.gif)

**Comment by samreid** [comment]
Good find, thanks!

**Comment by samreid** [comment]
Did you mean to mark this comment for https://github.com/phetsims/circuit-construction-kit-common/issues/796 ?  Also, in any case I will probably move the report to a new issue.  Can this one be closed?  It is about a cursor hand incorrectly showing over the empty voltmeter charts in rc.1.

**Comment by KatieWoe** [comment]
No, I hadn't gotten to that issue yet. I just noticed the differing behavior when all things were removed from rc.1 and thought it was this issue.
Closing
